docs: add contributing.md
expressjs/.github pull request #10
Opened 2024-11-15 22:05 UTC by bjohansebas

This is part of adding the documentation that can be inherited from this repository. It is the same content as in https://github.com/expressjs/express/blob/master/Contributing.md, excluding https://github.com/expressjs/express/pull/6087 and https://github.com/expressjs/express/pull/6033.

2024-11-15 22:05 UTC, bjohansebas commented
cc: @expressjs/express-tc

2024-11-16 15:10 UTC, bjohansebas commented
Maybe we want the main contributing to be in admin and follow the style in Node.js.

Node.js admin: https://github.com/nodejs/admin/blob/main/CODE_OF_CONDUCT.md
Node.js .github: https://github.com/nodejs/.github/blob/main/CODE_OF_CONDUCT.md

2025-01-14 19:52 UTC, wesleytodd requested changes
I dont like that added complexity. I was thinking we should make the `.github` repo the source for all we can. Honestly the name of the repo doesn't really matter as long as the docs are in the right place and the links are all correct. 

My main concern with this current form is that we dont have a good concept in here of the difference between contributing to `express` vs all the other packages. I think we should keep this in a branch and open PRs against it here until we are satisfied. This whole consolidation effort was one of the main things I wanted to do soon, so let me just leave this comment here and circle back in a week or so.

2025-01-14 19:56 UTC, ctcpip commented
Agree with Wes.  Frankly, we have a backlog of updating the contributing guide, as well as the security policy -- something we delayed doing until after the audit was complete and we were in 2025.

2025-03-30 02:18 UTC, bjohansebas commented
cc: @expressjs/express-tc

2025-04-11 15:19 UTC, wesleytodd approved these changes
Anything to pull this out of the `express` repo is good, but I do think the governence docs are not supported by GH to show in every repo, and also they apply for us to all three orgs, so we may be better off with that one in `discussions` than here.

2025-04-12 17:09 UTC, bjohansebas commented
> I do think the governence docs are not supported by GH to show in every repo

Yeah, even opening it on GitHub so they support this, since they show it as if they were going to do it.

https://github.com/orgs/community/discussions/155344

2025-04-17 15:11 UTC, wesleytodd requested changes

2025-04-17 15:11 UTC, wesleytodd commented on CONTRIBUTING.md
> +Use the correspondingly named branch, e.g. `5.0`, for anything intended for
```suggestion
Use the correspondingly named branch, e.g. `6.x`, for anything intended for
```

2025-04-17 15:11 UTC, wesleytodd commented on CONTRIBUTING.md
> +1. [Create an issue](https://github.com/expressjs/express/issues/new) for the
Since this will be fore all the repos, we probably need to fix up this section to remove the `express` specific references. Either that or we make this section "contributing to express" and add a section for the other repos below.

2025-04-17 15:11 UTC, wesleytodd commented on CONTRIBUTING.md
> +## Issues which are questions
We might also want to mention using `discussions` instead of `issues` for these.

2025-05-21 15:30 UTC, wesleytodd approved these changes
I am making a few edits to hopefully get this landed.

2025-05-21 15:30 UTC, wesleytodd commented on CONTRIBUTING.md
> +Open issues for the expressjs.com website in https://github.com/expressjs/expressjs.com.
```suggestion
Open issues for the expressjs.com website in https://github.com/expressjs/expressjs.com.

For issues in other Express managed repos (everything in `expressjs`, `pillarjs` or `jshttp` other than `expressjs/express`), be sure to check their contributing guide and open issues and PRs in the appropriate repository.
```

2025-05-21 15:30 UTC, wesleytodd commented on CONTRIBUTING.md
> +1. [Create an issue](https://github.com/expressjs/express/issues/new) for the
I am pretty sure the best best is to remove these links. I added a not above, but I think folks may accidentally not realize it and open issues from these links in `express` when they meant to in other repos. I am just going to remove it for now and we can add it back if we figure out a good way.

2025-05-21 15:30 UTC, wesleytodd commented on CONTRIBUTING.md
> +1. [Create an issue](https://github.com/expressjs/express/issues/new) for the
```suggestion
1. Create an issue for the
```

2025-05-21 15:30 UTC, wesleytodd commented on CONTRIBUTING.md
> +2. Create your own [fork](https://github.com/expressjs/express) on GitHub, then
```suggestion
2. Create your own fork on GitHub, then
```

2025-05-21 15:30 UTC, wesleytodd commented on CONTRIBUTING.md
> +us to understand and reproduce your issue, it will be closed.
```suggestion
us to understand and reproduce your issue, it will be closed.

If your question meets all of the above requirements but you do not believe it needs to be looked at
by the maintainers
(for example, if you are just looking for community input) please open it as a discussion topic instead
of an issue. If you
are unsure and open an issue, we may move it to discussions if we triage them and decide they do
not need high
visibility or maintainer input. 
```

2025-05-21 19:26 UTC, UlisesGascon approved these changes

2025-05-21 19:37 UTC, ctcpip approved these changes

2025-05-21 23:48 UTC, merged