add Code of Conduct
expressjs/.github pull request #8
Opened 2024-11-12 00:32 UTC by bjohansebas

This adds the code of conduct so that all repositories that don't have this file yet will have it and it will be up to date. It also resolves https://github.com/bjohansebas/codemod/issues/12#issuecomment-2469038159.

2024-11-12 00:33 UTC, bjohansebas commented
cc: @expressjs/express-tc

2024-11-12 12:54 UTC, wesleytodd approved these changes

2024-11-15 15:59 UTC, UlisesGascon approved these changes

2024-11-15 15:59 UTC, UlisesGascon commented on Code-Of-Conduct.md
> +email: express-coc@lists.openjsf.org
Are we sure that this email list is working/updated?

2024-11-15 15:59 UTC, UlisesGascon commented on Code-Of-Conduct.md
> +coc-escalation@lists.openjsf.org.
Are we sure that this email list is working/updated?

2024-11-15 16:07 UTC, wesleytodd commented
Good call on the emails. [Same comments I made here](https://github.com/expressjs/admin/pull/6#discussion_r1838249553) but I missed them in this PR.

2024-11-15 16:15 UTC, ctcpip requested changes
please rename the file to:  `CODE_OF_CONDUCT.md`

2025-01-08 21:46 UTC, bjohansebas commented
Any update on the emails?

2025-01-09 00:32 UTC, wesleytodd commented
I dont have one now, but I can work on this tomorrow. It shouldn't take too much to get these updated.

2025-02-18 20:26 UTC, bjohansebas commented
any update?

2025-02-18 20:37 UTC, wesleytodd commented on Code-Of-Conduct.md
> +coc-escalation@lists.openjsf.org.
That email list is working, but I have not updated it. Right now it is a spam honey pot and I had to disable the moderation setting for myself on it because I couldn't check all of that.

2025-02-18 20:38 UTC, wesleytodd commented
It is the right email, but we need something else in place for spam moderation because we should not all be in there checking it and it was getting nearly 1 email a day that was spam when I enabled the moderator setting for myself. This would be a good discussion to have on a TC meeting or working session to figure out a plan for.

2025-02-18 21:02 UTC, bjohansebas commented on Code-Of-Conduct.md
> +coc-escalation@lists.openjsf.org.
I think you were referring to the comment above, because this one is from CPC.

2025-03-17 20:41 UTC, ctcpip approved these changes

2025-03-17 21:20 UTC, ctcpip commented
discussed at TC meeting today. we are merging since there are no actual changes to the CoC; there is nothing new, etc.  we will create a separate issue to resolve the email

2025-03-17 21:20 UTC, merged